modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="vadersrandomadditions"
version="1.0.0"
displayName="Vader'sRandomAdditions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="karstenvader, MCreator"

[[dependencies.vadersrandomadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



